// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Web.Models
{
    public partial class NewsArticle
    {
        public const string Codename = "news_article";
        public const string ArticleDateCodename = "article_date";
        public const string ContentCodename = "content";
        public const string DisciplinesCodename = "disciplines";
        public const string ImageCodename = "image";
        public const string MetadataMetaDescriptionCodename = "metadata__meta_description";
        public const string MetadataMetaTitleCodename = "metadata__meta_title";
        public const string MetadataOgDescriptionCodename = "metadata__og_description";
        public const string MetadataOgImageCodename = "metadata__og_image";
        public const string MetadataOgTitleCodename = "metadata__og_title";
        public const string MetadataTiwtterCreatorCodename = "metadata__tiwtter_creator";
        public const string MetadataTwitterDescriptionCodename = "metadata__twitter_description";
        public const string MetadataTwitterImageCodename = "metadata__twitter_image";
        public const string MetadataTwitterSiteCodename = "metadata__twitter_site";
        public const string MetadataTwitterTitleCodename = "metadata__twitter_title";
        public const string PersonasCodename = "personas";
        public const string SitemapCodename = "sitemap";
        public const string SynopsisCodename = "synopsis";
        public const string TitleCodename = "title";
        public const string TypeOfNavigationCodename = "type_of_navigation";
        public const string UrlSlugCodename = "url_slug";

        public DateTime? ArticleDate { get; set; }
        public IRichTextContent Content { get; set; }
        public IEnumerable<ITaxonomyTerm> Disciplines { get; set; }
        public IEnumerable<IAsset> Image { get; set; }
        public string MetadataMetaDescription { get; set; }
        public string MetadataMetaTitle { get; set; }
        public string MetadataOgDescription { get; set; }
        public IEnumerable<IAsset> MetadataOgImage { get; set; }
        public string MetadataOgTitle { get; set; }
        public string MetadataTiwtterCreator { get; set; }
        public string MetadataTwitterDescription { get; set; }
        public IEnumerable<IAsset> MetadataTwitterImage { get; set; }
        public string MetadataTwitterSite { get; set; }
        public string MetadataTwitterTitle { get; set; }
        public IEnumerable<ITaxonomyTerm> Personas { get; set; }
        public IEnumerable<ITaxonomyTerm> Sitemap { get; set; }
        public string Synopsis { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
        public IEnumerable<ITaxonomyTerm> TypeOfNavigation { get; set; }
        public string UrlSlug { get; set; }
    }
}